#!/usr/bin/env sh

# Load nvm if available (common Node.js version manager)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Add common Node.js paths
export PATH="/Users/luke/Library/Application Support/JetBrains/IntelliJIdea2025.2/node/versions/24.11.0/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

npx lint-staged
